[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install torch --index-url https://download.pytorch.org/whl/cpu",
  "pip install -r requirements-web.txt"
]

[start]
cmd = "python web_start.py"
