# Start from a lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy function code
COPY . .

# Set environment variables
ENV EVENT="{}"
ENV CONTEXT="{}"

CMD ["sleep", "infinity"]